name: firebase_game_services_platform_interface
description: A common platform interface for the firebase_game_services package.
version: 2.2.1
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ">=2.1.4 <3.0.0"
  firebase_auth: ">=4.6.2 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1