name: firebase_game_services_platform_interface
description: A common platform interface for the firebase_game_services package.
version: 0.0.5
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ^2.1.2
  firebase_auth: ^3.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1