name: firebase_game_services
description: A Flutter package, linking Google's Play Games and Apple's Game Center with Firebase.
version: 0.0.4
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface: ^0.0.2
  #  path: ../firebase_game_services_platform_interface/
  firebase_game_services_apple: ^0.0.4
  #  path: ../firebase_game_services_apple/
  firebase_game_services_google: ^0.0.4
  #  path: ../firebase_game_services_google/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_game_services_google
      ios:
        default_package: firebase_game_services_apple
      macos:
        default_package: firebase_game_services_apple
      # linux:
      #   default_package: firebase_game_services_linux
      # web:
      #   default_package: firebase_game_services_web
      # windows:
      #   default_package: firebase_game_services_windows