name: firebase_game_services
description: A Flutter package, linking Google's Play Games and Apple's Game Center with Firebase.
version: 2.1.2
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface: ^2.1.0
  #  path: ../firebase_game_services_platform_interface/
  firebase_game_services_apple: ^2.1.0
  #  path: ../firebase_game_services_apple/
  firebase_game_services_google: #^2.1.3
   path: ../firebase_game_services_google/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_game_services_google
      ios:
        default_package: firebase_game_services_apple
      macos:
        default_package: firebase_game_services_apple
      # linux:
      #   default_package: firebase_game_services_linux
      # web:
      #   default_package: firebase_game_services_web
      # windows:
      #   default_package: firebase_game_services_windows