name: firebase_game_services_apple
description: The Apple implementation of firebase_game_services.
version: 0.0.1
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface: ^0.0.1
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  plugin:
    implements: firebase_game_services
    platforms:
      ios:
        pluginClass: FirebaseGameServicesApplePlugin
      macos:
        pluginClass: FirebaseGameServicesApplePlugin