name: firebase_game_services_apple
description: The Apple implementation of firebase_game_services.
version: 0.1.2
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface: ^0.1.2
  # path: ../firebase_game_services_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
flutter:
  plugin:
    implements: firebase_game_services
    platforms:
      ios:
        pluginClass: FirebaseGameServicesApplePlugin
      macos:
        pluginClass: FirebaseGameServicesApplePlugin