name: firebase_game_services_apple
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface:
    path: ../firebase_game_services_platform_interface/
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  plugin:
    implements: firebase_game_services
    platforms:
      ios:
        pluginClass: FirebaseGameServicesApplePlugin
      macos:
        pluginClass: FirebaseGameServicesApplePlugin