name: firebase_game_services_google
description: The Google implementation of firebase_game_services.
version: 2.2.0-rc.3
homepage: https://github.com/jonafeucht/firebase_game_services

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_game_services_platform_interface: ^2.2.0-rc.1
  #  path: ../firebase_game_services_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: firebase_game_services
    platforms:
      android:
        package: tiltedcu.be.firebase_game_services_google
        pluginClass: FirebaseGameServicesGooglePlugin