name: CI
on:
    pull_request:
      branches:
        - main
        - develop
    push:
      branches:
        - develop

defaults:
  run:
    working-directory: packages/firebase_game_services/example

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter build appbundle